version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "5050:5050"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb+srv://adithi:Shrouthy1999@cluster0.7frkuxc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - UX_MODEL=hf 
      - HF_HOME=/opt/hf-cache
      - TRANSFORMERS_CACHE=/opt/hf-cache
    volumes:
      - hf_cache:/opt/hf-cache
      - ./server:/app  

  frontend:
    build:
      context:  ./client
    ports: ["3000:3000"]
    stdin_open: true
    tty: true
    command: ["npm", "start"]
    depends_on: [backend]

volumes:
    hf_cache: